# Generated by Django 5.1 on 2024-10-29 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OlympicsData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("City", models.TextField(max_length=200)),
                ("Year", models.IntegerField()),
                ("Sport", models.TextField(max_length=200)),
                ("Discipline", models.TextField(max_length=200)),
                ("Event", models.TextField(max_length=200)),
                ("Athlete", models.TextField(max_length=200)),
                ("Gender", models.TextField(max_length=200)),
                ("Country_Code", models.TextField(max_length=3)),
                ("Country", models.TextField(max_length=200)),
                ("Event_gender", models.TextField(max_length=1)),
                ("Medal", models.TextField(max_length=100)),
            ],
        ),
    ]
